name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run linting
      run: |
        uv run ruff check eyes/
        uv run black --check eyes/
    
    - name: Run tests
      run: uv run pytest
    
    - name: Test build (Unix)
      if: runner.os != 'Windows'
      run: ./bin/build
    
    - name: Test build (Windows)
      if: runner.os == 'Windows'
      run: uv run pyinstaller --onefile --console --name eyes --paths eyes --hidden-import plyer.platforms.macosx.notification --hidden-import plyer.platforms.win.notification eyes/cli.py
    
    - name: Test executable help
      run: ./dist/eyes --help